### ISSUE TITLE
I have a website that needs authentication with username and password. Is it possible to authenticate a website and then run linkinator?

### ISSUE THREAD

**Issue by gauravgandhi1315** [JustinBeckwith/linkinator#536] opened 2023-01-27 05:25 UTC

**Comment by domdomegg** [comment] 2023-05-23 16:02
Not currently.

Duplicate of https://github.com/JustinBeckwith/linkinator/issues/202

**Comment by JustinBeckwith** [comment] 2024-06-02 16:11
Yup, tracking this over in #202

**Closed by JustinBeckwith** 2024-06-02 16:11 UTC
